# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# [START gke_boa_kubernetes_manifests_accounts_db_service_accounts_db]
apiVersion: v1
kind: Service
metadata:
  name: accounts-db
#  labels:
#    app: accounts-db
#    tier: db
spec:
  ports:
    - port: 5432
      name: tcp
      targetPort: 5432
      protocol: TCP
  externalIPs:
    - 10.20.2.11
#  selector:
#    app: accounts-db
#    tier: db
# [END gke_boa_kubernetes_manifests_accounts_db_service_accounts_db]
---
# [START gke_boa_kubernetes_manifests_accounts_db_configmap_accounts_db_config]
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  labels:
    app: accounts-db
data:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: aloy#2018
  #ACCOUNTS_DB_URI: postgresql://postgres:aloy#2018@10.20.2.11:5432/accounts-db
  ACCOUNTS_DB_URI: "postgresql://admin:admin@localhost:5432/accounts-db"
  #ACCOUNTS_DB_URI: "postgresql+psycopg2://localhost:5432/accounts-db"
# [END gke_boa_kubernetes_manifests_accounts_db_configmap_accounts_db_config]